import { useState, useEffect } from "react";
import { fmt } from "../../game/constants";

// ═══ SHARED COMPONENTS ════════════════════════════════════════
export function Confetti({trigger,isDragon}){
  const[ps,setPs]=useState([]);
  useEffect(()=>{if(!trigger)return;const cols=isDragon?["#c264ff","#e8b4ff","#9b4de0","#f0c0ff"]:["#f5c842","#00e5b0","#ff3d5a","#ffd700","#fff"];const np=Array.from({length:isDragon?80:50},(_,i)=>({id:Date.now()+i,left:Math.random()*100,sz:6+Math.random()*8,col:cols[Math.floor(Math.random()*cols.length)],round:Math.random()>.5,dur:1.5+Math.random()*2.5,del:Math.random()*.6}));setPs(np);setTimeout(()=>setPs([]),4500);},[trigger]);
  return <div style={{position:"fixed",inset:0,pointerEvents:"none",zIndex:1000,overflow:"hidden"}}>{ps.map(p=><div key={p.id} className="conf" style={{left:`${p.left}%`,width:p.sz,height:p.sz,background:p.col,borderRadius:p.round?"50%":"2px",animationDuration:`${p.dur}s`,animationDelay:`${p.del}s`}}/>)}</div>;
}
export function DragonOverlay({show,prize,onClose,preview=false}){if(!show)return null;return <div style={{position:"fixed",inset:0,zIndex:9999,background:"rgba(5,7,15,.96)",display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column",gap:18}}>{preview&&<div style={{position:"absolute",top:24,left:0,right:0,textAlign:"center",fontSize:13,letterSpacing:2,color:"#8a96aa",textTransform:"uppercase"}}>🔍 Prévia — não é uma rodada real</div>}<div className="dF" style={{fontSize:118}}>🐉</div><div className="cd" style={{fontSize:37,fontWeight:900,background:"linear-gradient(90deg,#c264ff,#e8b4ff,#c264ff)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",textAlign:"center"}}>DRAGÃO SAGRADO!</div><div className="cn" style={{fontSize:21,color:"#c264ff",textAlign:"center",opacity:.8}}>×100 — {preview?`Exemplo: apostando ${fmt(prize/100)}, você ganharia`:"Você ganhou"} {fmt(prize)}!</div>{preview&&<div style={{fontSize:13,color:"#6a7a9a",textAlign:"center",maxWidth:320}}>Chance real: ~1 em 1 milhão de giros. Mesma chance no modo demo e na conta real.</div>}<button onClick={onClose} style={{marginTop:8,padding:"11px 32px",background:"linear-gradient(135deg,#c264ff,#9b4de0)",color:"#fff",border:"none",borderRadius:12,fontFamily:"'Cinzel',serif",fontSize:18,fontWeight:700,cursor:"pointer",letterSpacing:1}}>{preview?"FECHAR":"RECOLHER O TESOURO"}</button></div>;}
